  # A conda environment with packages necessary for event types study
name: event-types
channels:
  - default
dependencies:
  - python=3.7
  - pip
  - ipython
  - jupyter
  - numpy>=1.17
  - numpydoc
  - matplotlib
  - pytables
  - pandas
  - time
  - astropy
  - scikit-learn
  - seaborn
  - conda-forge::uproot
